# Generated by Django 4.0.2 on 2022-02-23 05:35

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(blank=True, editable=False, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='', verbose_name='фотография'),
        ),
    ]
