# Generated by Django 4.0.2 on 2022-03-19 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measureweight',
            name='weight',
            field=models.FloatField(verbose_name='вес в граммах'),
        ),
    ]
