# Generated by Django 4.0.2 on 2022-04-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_measureweight_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='after',
            field=models.TextField(blank=True, verbose_name='завершение'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='steps',
            field=models.TextField(blank=True, verbose_name='подготовка'),
        ),
    ]
