# Generated by Django 4.0.4 on 2022-07-04 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='state',
            field=models.CharField(choices=[('new', 'новый'), ('accepted', 'принят'), ('rejected', 'отклонен')], default='new', max_length=8, verbose_name='состояние'),
        ),
    ]
