# Generated by Django 4.0.2 on 2022-02-13 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('volume', models.PositiveIntegerField(null=True, verbose_name='объем в миллилитрах')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('duration', models.DurationField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('crust', models.CharField(choices=[('light', 'Light'), ('medium', 'Medium'), ('dark', 'Dark')], max_length=8)),
                ('description', models.TextField()),
                ('weight', models.PositiveIntegerField(verbose_name='вес в граммах')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='default.program')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='default.ingredient')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='default.measure')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.recipe')),
            ],
            options={
                'ordering': ['recipe', 'position'],
            },
        ),
        migrations.CreateModel(
            name='MeasureWeight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.PositiveIntegerField(verbose_name='вес в граммах')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.ingredient')),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.measure')),
            ],
        ),
        migrations.AddConstraint(
            model_name='recipeingredient',
            constraint=models.UniqueConstraint(fields=('recipe', 'position'), name='unique_recipeingredient_position'),
        ),
        migrations.AddConstraint(
            model_name='measureweight',
            constraint=models.UniqueConstraint(fields=('ingredient', 'measure'), name='unique_ingredient_measure'),
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name'], 'verbose_name': 'ингредиент', 'verbose_name_plural': 'ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='measure',
            options={'ordering': ['name'], 'verbose_name': 'единицу измерения', 'verbose_name_plural': 'единицы измерения'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['name'], 'verbose_name': 'программу', 'verbose_name_plural': 'программы'},
        ),
        migrations.AddField(
            model_name='measure',
            name='short_name',
            field=models.CharField(default='', max_length=32, verbose_name='краткое наименование'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measure',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.DurationField(verbose_name='продолжительность, мин'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='measure',
            name='volume',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='объем в миллилитрах'),
        ),
        migrations.AlterModelOptions(
            name='measureweight',
            options={'verbose_name': 'вес ЕИ', 'verbose_name_plural': 'вес ЕИ'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['name'], 'verbose_name': 'рецепт', 'verbose_name_plural': 'рецепты'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredient',
            options={'ordering': ['recipe', 'position'], 'verbose_name': 'ингредиент рецепта', 'verbose_name_plural': 'ингредиенты рецепта'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='default.RecipeIngredient', to='default.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='crust',
            field=models.CharField(choices=[('light', 'Светлая'), ('medium', 'Средняя'), ('dark', 'Темная')], max_length=8, verbose_name='корочка'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=64, unique=True, verbose_name='наименование'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='default.program', verbose_name='программа'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='default.ingredient', verbose_name='ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='measure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='default.measure', verbose_name='ЕИ'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='position',
            field=models.PositiveIntegerField(editable=False, verbose_name='№'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='кол-во'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='default.recipe', verbose_name='рецепт'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measures',
            field=models.ManyToManyField(through='default.MeasureWeight', to='default.Measure'),
        ),
    ]
